### ISSUE TITLE
[MISP] Combination of tags filters

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#102]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Currently the MISP connector allows to import events if they have a specific tag.
It is not possible to import based on a combination of tags

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

Allow to import MISP events based on a combination of tags.
Allow the said tags to be opt-in or opt-out.

For example: 

import if <tag a> OR <tag b> OR <tag c>

do not import if <tag a> OR <tag b>

etc

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by rhaist** [comment]
Based on the configuration you can use `MISP_IMPORT_TAGS` to do that.

https://github.com/OpenCTI-Platform/connectors/tree/master/misp#configuration

Example: `MISP_IMPORT_TAGS: "!searchtag:1337"` --> do not import events with tag 1337

**Comment by Fred-certeu** [comment]
Thanks!
Will try it.

**Comment by SamuelHassine** [comment]
@Fred-certeu does this solution worked? We will start new works around the MISP connector so I need to know if this is something I need to implement.

**Comment by csandu-certeu** [comment]
Thanks @rhaist  and sorry for late reply. We have tested it but the negation is not working. I might be wrong, but by checking the connector's code https://github.com/OpenCTI-Platform/connectors/blob/master/misp/src/misp.py#L129, it seems like only OR condition is being build to be passed to "misp.build_complex_query"

"and_paramters" and "not_parameters" are not being built: https://pymisp.readthedocs.io/en/latest/modules.html?highlight=build#pymisp.PyMISP.build_complex_query

In this case, by passing something like   MISP_IMPORT_TAGS="!tag1, !tag2", it will create an OR and therefore the logic won't work. 
And by passing      - MISP_IMPORT_TAGS="!tag1", I believe the connector will just search for that exact tag, since the "not_parameters" is not built.

**Comment by SamuelHassine** [comment]
Ok @csandu-certeu we will fix that.

**Comment by SamuelHassine** [comment]
This is now fixed.
