### ISSUE TITLE
Issue: Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"? 

### ISSUE THREAD

**Issue by mhuangdesign** [OpenCTI-Platform/connectors#1064]
I'm trying to deplpy misp connector to opencti platform using docker compose yaml file(https://www.youtube.com/watch?v=AU5XvjvWyUQ) , and get this error: Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?

**Comment by ringenbp** [comment]
For those who will face the same problem in the future:
This 'Cannot query field "listen_routing" issue is due to the fact that your deployment is not consistent. The pycti api call is requesting a field that does (or did) NOT exist in the deployed version.
The solution is to update your stack with a consistent docker-compose (typically choose a version and don‘t expect it to work with earlier services). That‘s what versions are done for.

I hope this helps
