### ISSUE TITLE
[LastInfoSec] Create the connector

### ISSUE THREAD

**Issue by remydewa** [OpenCTI-Platform/connectors#111]
**Feature description**

**LastInfoSec** is a young startup founded by three cyber defence experts. Their main objective is to become a leader in automated intelligence on subjects like cybercrime and cyberwar.

**LastInfoSec's Threat Feed** is a data feed that makes it easier to detect threats within the information system. It contains enriched compromised evidences in order to reduce the time of threat analysis once detected.
Their automated collection, analysis and correlation engines make data accessible on average 24 hours before our competitors.
LastInfoSec's technology continuously inventories and evaluates the data sources available through different channels on the internet : social networks, specialized websites, darknet and deep web.

More information on their website: [LastInfoSec](https://www.lastinfosec.com/en/)

**Comment by SamuelHassine** [comment]
@remydewa please can you make a PR with much more documentation in the README? 

- Description of the LastInfoSec feed
- Description of the parameters (even the default ones)
- Maybe a logo/header

**Comment by remydewa** [comment]
@SamuelHassine I did it in this pull request:
https://github.com/OpenCTI-Platform/connectors/pull/122

Don't hesitate to come back to me if needed.

Many thanks,

Rémy

**Comment by fsnormand** [comment]
Hello ,
I tested your modifications on our connector.
However, we have an error "dict could not use the encode function", because you deleted the json.dumps function to convert the dict to string.
I added the json.dumps but you changed the bundle STIX sent function too and now we cannot integrate data in the platform.
Could you fix these issues or rollback with the self.api.stix2.import_bundle_from_json function ?

**Comment by SamuelHassine** [comment]
I will fix this, is it possible to come on Slack channel and give us in private access to your API so we can do more tests?
