### ISSUE TITLE
Error Misp connector with old Misp instance

### ISSUE THREAD

**Issue by campeador** [OpenCTI-Platform/connectors#132]
## Description

{ Depend of MISP instance version the Misp connector will fail if you use the recommended PyMisp library. You have to use a older version of PyMisp like  2.4.114 -> https://pypi.org/project/pymisp/#history }

## Environment

1. OS:  {Ubuntu 16.08, etc. }
2. OpenCTI version: { OpenCTI 3.2.2 }
3. OpenCTI client: { frontend  }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Run Misp connector }

## Expected Output

{ No error at all. }

## Actual Output

{ lib/python3.7/site-packages/pymisp/api.py", line 1269, in get_user
    r.from_dict(**user['Role'])
KeyError: 'Role' }
 
## Additional information

{ Additional information: https://github.com/MISP/PyMISP/issues/523 }

**Comment by SamuelHassine** [comment]
@campeador we are sorry but for the moment we do not intend to maintain the MISP connector for old MISP versions, we will keep this connector up-to-date with the latest PyMISP lib.

You can still fork the connector and try to adapt it to older version, it should not be a big deal since we are using only one or two methods from the PyMISP lib (`search`), the rest of the connector is pure OpenCTI code.
