### ISSUE TITLE
[Misp-feed] Import status

### ISSUE THREAD

**Issue by annoyingapt** [OpenCTI-Platform/connectors#1830]
## Prerequisites

- [x] I read the [Deployment and Setup](https://filigran.notion.site/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://filigran.notion.site/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I'm trying to get some information around x_opencti_report_status, the misp-feed connector is using it and is passing the integer 2. Which I think is supposed to set the status to "In Progress" can someone confirm? Currently in my environment, the status is being set to "New" and I would like to import them as "In Progress". I have tried changing the integer to different values, but the status stays as "New". I'm not sure if this is a connector issue, a platform issue, or a resolved issue. I am running an old version 5.10.x which I do plan to upgrade to 5.12.x in the next month.

I've asked a few times on slack, but no one has been able to help so far.

## Environment

1. OS (where OpenCTI server runs): Portainer
2. OpenCTI version: 5.10.x
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Setup CIRCL using the MISP-Feed connector 
2. Reports imported with status of New

## Additional information

![image](https://github.com/OpenCTI-Platform/connectors/assets/55898651/c4f25547-98b0-452e-bc67-c55d10cce9ed)
![image2](https://github.com/OpenCTI-Platform/connectors/assets/55898651/ab2a8ef0-3fa3-4343-9c27-3c2f55b53537)

**Comment by annoyingapt** [comment]
I just added the Alienvault connector an noticed these reports are being ingested as New too, even if you change the ALIENVAULT_REPORT_STATUS=New variable. So I'm guessing this is a platform issue then?
![image](https://github.com/OpenCTI-Platform/connectors/assets/55898651/a0140b3a-d97f-44d6-b7a3-4f107ce3cd83)

**Comment by nino-filigran** [comment]
@helene-nguyen and @Megafredo would you know what is this x_open_cti_report_status and how to use it?

**Comment by helene-nguyen** [comment]
@nino-filigran, @annoyingapt, as you mentionned, `x_opencti_report_status` is the status and 2 is actually the order of the status `IN PROGRESS` **BUT** it is a deprecated usage that we need to remove.

The custom properties used now is `x_opencti_workflow_id` and it is available on Reports and Cases since the lastest version 6.0.1 of OpenCTI.

For your version of OpenCTI, you may find that the following steps will lead you to the result you are looking for.
When you import a report, you have a default workflow into OpenCTI that have been applied, you can find some details on the documentation:

- [Workflow status documentation](https://docs.opencti.io/latest/administration/entities/#workflow)

![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/122b6c37-78f3-4e17-9f2e-d68377adc07c)

And you can customize your workflow in your Settings > Customization > Report

There, you can change the order of the status, delete or add a new one:

![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/7f9e83a6-28dc-4d1c-bd85-263c26a17037)

Hope that helps :)

**Comment by annoyingapt** [comment]
Appreciate the response, so will a connector be able to import with a status of in progress or do I need to use automation to automatically change the  status once it is created?

**Comment by annoyingapt** [comment]
The following connectors use x_opencti_report_status. Do you have recommendations for the community supporting these connectors?

Kaspersky
Alienvault
Misp
Misp-feed
Cybersixgill
CrowdStrike
Crits

**Comment by annoyingapt** [comment]
So if I replace x_opencti_report_status with the x_opencti_workflow_id and the status id. I am able to change the status on ingestion. However, as the uuid is unique on every install, this isn't a feasible solution. If it is not currently possible, could this be considered in a future release.

**Comment by helene-nguyen** [comment]
@annoyingapt, about your questions:

> [...] will a connector be able to import with a status of in progress or do I need to use automation to automatically change the status once it is created?

It's a good practice to change the status workflow if you want to add a particular status after it has been created and not adding it in the connector even if you have this possibility.

As you mentionned, if you replaced `x_opencti_report_status` with the `x_opencti_workflow_id`, it will work but the uuid is unique on every install and it is not a long term solution.

> Do you have recommendations for the community supporting these connectors?

As the `x_opencti_report_status` is deprecated and doesn't work, the first step is to remove it from the custom properties.

@SamuelHassine, did I miss something?
