### ISSUE TITLE
[alienvault] Add labels on indicators & observables

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#184]
Hello,

Is it possible to add the same labels (tags) that are on a report on indicators & observables?

Thanks!

**Comment by maertv** [comment]
I think that it is possible to add the tags from the report as the labels to the indicators. However, I not sure that the labels can be added to the observables, because if I understand the STIX2 specification correctly then the _labels_ property is not applicable for the observables. For example, the properties section of the IPv4 Address object lists the _labels_ property under the Not Applicable Common Properties (https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_ta83c412bfsc).
