### ISSUE TITLE
[Hybrid Analysis] Unable to enrich TLP:CLEAR file observable

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#2062]
I have a MISP feed connector creating file observables with TLP:CLEAR marking. Hybrid Analysis is unable to enrich due to the below error. Another user on Slack has also seen the exact same issue. Removing the marking or using a different one, such as TLP:AMBER, allows enrichment.

![image](https://github.com/OpenCTI-Platform/connectors/assets/124377454/ac90964c-aaa0-4347-88a3-ce1cce98e64d)

**Comment by nino-filigran** [comment]
@Megafredo could you please check this out?
This is a connector under filigran support, so has higher priority than bugs under community support.

**Comment by Megafredo** [comment]
Hi @dominictory, during the investigation it turns out that there has been a relatively recent update of the Hybrid Analysis enrichment connector, if you wish you can see the changes made here :
https:// github.com/OpenCTI-Platform/connectors/commit/6ab349bfe64f0db88cb39fae4d93724503624cfd

I invite you to update the connector "Hybrid Analysis" as well as the platform, this should solve the problems you encountered with the markers, waiting for your return ;)

**Comment by nino-filigran** [comment]
@dominictory closing this ticket for now since I do not see any activity for a month. Though, if the above worked mention by @Megafredo did not solve your problem, feel free to re-open it.

**Comment by dominictory** [comment]
> @dominictory closing this ticket for now since I do not see any activity for a month. Though, if the above worked mention by @Megafredo did not solve your problem, feel free to re-open it.

No longer seeing this issue on 6.1.2 :)
