### ISSUE TITLE
Import document connector is stopping / blocking  if trying to process unsupported mime type

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#2249]
## Description

Import document connector is stopping / blocking  if trying to process unsupported mime type

1. Put "application/octet-stream" in the scope
2. Upload this file (after unzip):
[calc-exe.zip](https://github.com/user-attachments/files/15986696/calc-exe.zip)
3. Trigger the connector

=> Then try to trigger the connector on a PDF file, the connector is not processing anymore.

**Comment by helene-nguyen** [comment]
@SamuelHassine 
Currently the connector list all available mime types here:

https://github.com/OpenCTI-Platform/connectors/blob/fab4b7ab19bb78e42af39d576a936fe81fc382da/internal-import-file/import-document/src/reportimporter/constants.py#L1

And when it is not a supported mime type, the following error is displayed:

Due to this:

https://github.com/OpenCTI-Platform/connectors/blob/fab4b7ab19bb78e42af39d576a936fe81fc382da/internal-import-file/import-document/src/reportimporter/report_parser.py#L136

I suggest to remove from constant each MIME_X and create a list of mime types from the scope

` scope: 'application/pdf,text/plain,text/html,text/csv,text/markdown,application/octet-stream'`

What do you think ?

**Comment by helene-nguyen** [comment]
Following our discussion and tests by my side, importing another document works even after importing a document that don't have a format unsupported.
I close the issue for now and it can be re-opened if needed :)
