### ISSUE TITLE
[importDocument] - Unable to extract information from PDF with a watermarking image

### ISSUE THREAD

**Issue by romain-filigran** [OpenCTI-Platform/connectors#2469]
## Description

The connector's current implementation doesn't seem capable of extracting information from a PDF containing a watermarked image.

It seems that using the high-level "extract_text" method present in the "pdfminer" library solves the problem, but why not have used this directly instead of parsing element by element.

@SamuelHassine : Can we schedule a time to talk about this?

## Environment

OpenCTI version: 6.2.12

**Comment by jeFF0Falltrades** [comment]
Hi Filigran team!

I have found a possible workaround to this:

The primary issue appears to be in the [`_parse_pdf()` function of the ImportDocument Connector](https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-document/src/reportimporter/report_parser.py#L96-L113):

According to the[ `pdfminer` docs](https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html#topic-pdf-to-text-layout), `LTFigure` objects can also contain embedded text elements.

So because the current Connector only loops through the first layer of elements, here's what it finds on a document that is watermarked:

```

**Comment by jeFF0Falltrades** [comment]
Hi Filigran team!

I have found a possible solution to this:

The primary issue appears to be in the [`_parse_pdf()` function of the ImportDocument Connector](https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-document/src/reportimporter/report_parser.py#L96-L113):

According to the [ `pdfminer` docs](https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html#topic-pdf-to-text-layout), `LTFigure` objects can also contain embedded text elements.

So because the current Connector only loops through the first layer of elements, here's what it finds on a document that is watermarked, for example:



```
<LTFigure() 0.000,0.000,612.000,792.000 matrix=[1.00,0.00,0.00,1.00, (0.00,0.00)]>
<LTFigure() 0.000,0.000,612.000,792.000 matrix=[1.00,0.00,0.00,1.00, (0.00,0.00)]>
<LTFigure() 0.000,0.000,612.000,792.000 matrix=[1.00,0.00,0.00,1.00, (0.00,0.00)]>
```

On the other hand, if the code in `_parse_pdf()` is changed to something like this:

```python
for element in page_layout:
    if isinstance(element, LTFigure):
        for sub_element in element:
            print(sub_element)
        ....
```

You find the underlying text containers within the `LTFigure` elements:

```
<LTFigure() 0.000,0.000,612.000,792.000 matrix=[1.00,0.00,0.00,1.00, (0.00,0.00)]>
<LTTextBoxHorizontal(0) 296.540,745.600,607.000,785.344 'Text here\n'>
<LTTextBoxHorizontal(1) 174.320,575.796,453.102,597.816 'Text here\n'>
<LTTextBoxHorizontal(2) 287.720,554.654,336.632,565.634 'Text here\n'>
...
<LTFigure(Image) 14.250,649.410,597.250,752.310 matrix=[583.00,0.00,0.00,102.90, (14.25,649.41)]>
<LTRect 66.850,235.160,552.000,494.360>
<LTRect 65.350,233.660,553.500,495.860>
...
```

I'm going to leave it to your team to decide how you'd like to handle the recursive layout element parsing, but I believe if you just add another layer of iteration through elements - or make the parsing recursive through however many layers of elements - the Connector will discover much more text in documents that may have text embedded in `LTFigure` containers.

Please let me know if I can clarify anything above.
