### ISSUE TITLE
[ThreatFox] Create the connector

### ISSUE THREAD

**Issue by IOTech17** [OpenCTI-Platform/connectors#293]
Hi,

abuse.ch recently released their IOC platform threatfox : https://threatfox.abuse.ch/api/

https://threatfox.abuse.ch/export/

Could you create a connector as it is a high quality feed?

This need to include the tag of the Threat.

Thank you in advance.

**Comment by AC-WhiteGlint** [comment]
If you look at the csv file you can import different type of IOC : https://threatfox.abuse.ch/export/#csv

URL
sha256 or md5
IP port
Domain

This can replace the URLhause connector because this one came with proper tagging of the threat.

However will you create a new connector with option to import or not certain types of IOC or will you create different connector, one for each type of IOC?

**Comment by SamuelHassine** [comment]
Duplicate of #329.
