### ISSUE TITLE
[virustotal] Connector doesn't handle use cases very well when the allowed VT API quota is set to 1 request per day

### ISSUE THREAD

**Issue by harshil-95** [OpenCTI-Platform/connectors#500]
## Description

VirusTotal connector is having an Error in processing the messages received from API and hence does not create any observables.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 5.0.1
3. OpenCTI client: docker instance
4. Other environment details:
 
## Additional information

Docker container log - 
![image](https://user-images.githubusercontent.com/80265383/135640106-ed7b8c82-4152-432f-9110-db0e11c098aa.png)

Discussion with @nor3th on Slack - 
![image](https://user-images.githubusercontent.com/80265383/135639107-0657bd71-caa8-4ab2-aaa3-66912dc043e9.png)

**Comment by nor3th** [comment]
Hey @harshil-95 

Could you please share the Observable you want to enrich as a STIX 2 file? I am having issues reproducing the problem.

Thanks,

**Comment by harshil-95** [comment]
Hi @nor3th ,
There isn't anything in particular that I wanted to enrich. I had just configured the docker-compose.yml and created a separate user for the connector to work as default. While it did not work at all last week. Today it did upsert some documents in OpenCTI - 
![image](https://user-images.githubusercontent.com/80265383/136024483-ce1cb776-7223-4ba6-b8a4-a02d490de16e.png)

Also sharing the logs from today -
[_docker_connector-virustotal_1_logs.txt](https://github.com/OpenCTI-Platform/connectors/files/7285870/_docker_connector-virustotal_1_logs.txt)

As you can see in the logs, my query limit got exhausted even though there has not been a single lookup for any kind of enrichment and there is a long queue in connector status- 
![image](https://user-images.githubusercontent.com/80265383/136025176-0bf6460a-1a65-4319-b96a-609dc7adaa97.png)

**Comment by nor3th** [comment]
Hey

Is the connector able to interact with the rabbitmq instance? Seems like there's an issue there which causes the jobs to never finish. 

Regards

**Comment by harshil-95** [comment]
It is really weird because they say 100M+ requests per month but just 1 per day!
![image](https://user-images.githubusercontent.com/80265383/136802934-9f728d12-8333-4105-ac43-2238fe9012dd.png)

**Comment by nor3th** [comment]
ok, then it makes sense. The unfinished jobs have following reason.

Every time the connector is run and the quota is reached, the virustotal connector sleeps for an hour (https://github.com/OpenCTI-Platform/connectors/blob/master/internal-enrichment/virustotal/src/virustotal/virustotal.py#L99-L100) and then tries again. Meaning that for every enrichment attempt a new job will start and since your VT quota is maxed out for the day, all of them wait indefinitely until they finally talk to the API. 

I'll leave this issue open for now, since it's not the ideal situation to have that many idle jobs for the connector.

Regards,
