### ISSUE TITLE
Multiple Crowdstrike Organization

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [OpenCTI-Platform/connectors#540]
## Description

Dear all,
I had in an OpenCTI installation, multiple Crowdstrike identity (about ten), I can delete seven of them, but I can't delete or update  three of them.  All ten of them as the same STIX id
I want to delete them because I had some errors in worker log that it is trying to create Crowdstrike identity and it fails due to "Execution timeout, too many concurrent call on the same entities"

## Environment

1. OS (where OpenCTI server runs): docker swarm on ubuntu 5.0.3
2. OpenCTI version: 5.0.3
3. OpenCTI client: frontend

**Comment by richard-julien** [comment]
Hi @GiuseppeLaurenza,

It will be difficult to help with your description.
But first strange stuff is "All ten of them as the same STIX id" because same stix_id should merge the identities. They share the standard_id or the other_stix_ids ?

If its other_stix you can try to cleanup this situation through the UI

![image](https://user-images.githubusercontent.com/285555/141455938-429020ad-ed04-4d9a-90f1-e114cbf9dfff.png)

After cleaning to prevent stixId sharing, you can retry to inject the identities.

**Comment by GiuseppeLaurenza** [comment]
It was the standard stix id
I know it was strange to had various equals element. I think it was some error in the merging
To try to solve the problem I delete all these entries directly from elastic
Now I had only one CrowdStrike element
I am monitoring the system in order to identify if the problem is there yet

**Comment by richard-julien** [comment]
Hi cool. Really interested if you are able to reproduce this situation.

**Comment by GiuseppeLaurenza** [comment]
I found that there were also a malware XORDDOS with three entries with the same STIX_id
Deleted them and now the platform appears to work without problem.
Probably during deploy/update of the last days there were some errors that lead to the "multiplication" of some entities and this fact cause all the problem of concurrency that I had.
Unfortunatelly I can't discover how it happens and how to reproduce the situation
