### ISSUE TITLE
Fix antlr version

### ISSUE THREAD

**Issue by rhaist** [OpenCTI-Platform/connectors#62]
I am currently getting the following error with this connector:

```
ANTLR runtime and generated code versions disagree: 4.7.2!=4.8
```

Could it be, that the hard coded 4.7.2 version needs to be removed @maertv ?

https://github.com/OpenCTI-Platform/connectors/blob/5d86c52ff596d447baeb03b2648a86ade3752362/alienvault/Dockerfile#L12

**Comment by maertv** [comment]
Yes, I believe that the hard coded version is causing the error.

I removed the hard coded version from the Dockerfile while working on issue #55 (see the PR #61).

**Comment by rhaist** [comment]
But it is not part of the requirements.txt and seems to be a hard dependency.
Maybe add `antlr4-python3-runtime` there?

**Comment by maertv** [comment]
> But it is not part of the requirements.txt and seems to be a hard dependency.
> Maybe add `antlr4-python3-runtime` there?

I do not think that _antlr4-python3-runtime_ needs to be in the _requirements.txt_ or in the _Dockerfile_.

It is possible that I am missing something but the reason why I added `antlr4-python3-runtime==4.7.2` (the _requirements.txt_ would have been the correct place) was because of https://github.com/oasis-open/cti-pattern-validator/issues/67. The issue should be fixed in the latest version (https://github.com/oasis-open/cti-pattern-validator/releases/tag/v1.3.0) and therefore there should be no reason to specify _antlr4-python3-runtime_  version.

Do you still get the error if you remove the line in question from the _Dockerfile_?

**Comment by maertv** [comment]
The modifications made for the #55 are now in the _master_ branch.

@rhaist, can you please check if the error is still present in the _master_ branch?

**Comment by rhaist** [comment]
Testing with alienvault:rolling the problem seems to be fixed!
Thanks!

**Comment by maertv** [comment]
@rhaist , thank you!

Closing the issue.
