### ISSUE TITLE
[Mandiant] Mscore is not taken into account

### ISSUE THREAD

**Issue by Moloson** [OpenCTI-Platform/connectors#736]
## Description

Actually, the Mandiant plugin pull IOCs presents without taking account of the mscore, meaning we cannot know if the IOC is revelant for them or not (based on their mscore) when looking at them with OpenCTI.

Should it be possible to add in the query a parameter (using ENV vars) to define the minimum mscore we would like to import into OpenCTI ? Or implement the same thing as the Crowdstrike connector (having the capacity to add a label for low confidence IOC) ?

## Environment

OS (where OpenCTI server runs): Ubuntu 20.04
OpenCTI version: 5.3.7
OpenCTI client: Frontend
Other environment details: docker

**Comment by annoyingapt** [comment]
Is there a chance someone could look at implementing this. Currently the Mandiant feed has low confidence domains and there is an expectation to use mscore when querying the API for indicators. Having the mscore variable in the config would be a bonus. twitter.com has been in Mandiant since October :-/

![image](https://user-images.githubusercontent.com/55898651/212589877-58b7047a-9061-474c-96ac-7bcce1176101.png)
