### ISSUE TITLE
[Mandiant] Report state time is in the future. 

### ISSUE THREAD

**Issue by RaulSokolova** [OpenCTI-Platform/connectors#980]
## Description

We are missing reports due to the state time, which if you are running the connector every 30 mins, the state time will get pushed every time by one hour. Which can take the connector to easily be a day or so in the future. 

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Set MANDIANT_INTERVAL = 5
Check how the state epoch time of the connector gets pushed to the future each the connector runs.

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

To be exactly the time it ran or at least a couple of hours behind to ensure we do not miss any reports.

## Actual Output

Doesn't ingest reports.

**Comment by gbikram** [comment]
Thanks for creating this issue - I was about to create a new one. Just adding additional information provided by a teammate for further reference:

### Context
The Mandiant connector queries the vulnerability, indicator, and report apis by querying for a specific window between 2 timestamps in epoch seconds. The latest timestamp which has been queried is stored in the opencti connector state, for example:
{"actor": 300, "malware": 4840, "vulnerability": 1674655807, "indicator": 1674655809, "report": 1674655807}
When the connector runs it retrieves the latest timestamp from the state and makes a query for the next window:
https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/mandiant/src/mandiant.py#L607

There is a bug in the flow control for the `_import_vulnerability` `_import_indicator` and `_import_report` functions, which causes the state to be set to a timestamp in the future, resulting in the connector never successfully querying for threat data.

### What Should Happen
The connector should query for threat data, stopping when it reaches the present timestamp, and then set the state to the current time. Then the next time the connector runs it should query for the period of time after the stored timestamp, again stopping when it reaches the present.

### What Actually Happens
The connector queries for threat data, stopping when it hits the present. It then sets the state to a point in time in the future. The next time the connector runs it queries for a time window from a point in time which is still in the future to a point in time which is even further in the future. Then the connector sets the state to a point in time even further in the future. Eventually the stored timestamp creeps further and further into the future and the connector never successfully obtains threat data.

### Cause of the Issue
The issue is caused by 2 mistakes in the flow control of the `_import_vulnerability`, `_import_indicator`, and `_import_report functions`. The first mistake is that the connector always makes at least 1 query, even if the start_ epoch is in the future. This means that if the stored start_epoch happens to be in the future it will make a query for a time window which hasn’t occurred yet. The second mistake is that once the connector queries until it reaches the present (end_epoch > time.time() ), it will store the end_epoch, which is in the future, instead of storing the  present time. (https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/mandiant/src/mandiant.py#L690)

Even if the connector had a very long interval between runs, such that the stored timestamp changed from being in the future to being in the past, there would still be data loss: if the connector runs at 100, stores 105, then runs again at 110, it will query from 105 onwards, missing any threat data published to the Mandiant API between 100 and 105.

### Solution
It is a simple fix: ensure that if the connector ever queries a window which ends in the future (i.e. `end_epoch > time.time()` ) then the connector stops querying, and also stores the state as the present time, NOT the end_epoch. 
Taking the `_import_vulnerability` function as an example, I would change **line 690** of 5.5.2 mandiant.py from this:
                `start_epoch = end_epoch`
to this:
                `start_epoch = min(end_epoch, int(time.time()))`
